### ISSUE TITLE
clustering issues

### ISSUE THREAD

**Issue by giladDAN** [galsinai128/parking#1]
what selected the size of cluser vs the marker, this image show them both ?

![image](https://user-images.githubusercontent.com/8138011/62388536-37dc8000-b566-11e9-98b8-2aa49739bae8.png)

**Comment by galsinai128** [comment]
what do you mean selected?
if you'll zoom in threw the cluster it will be diverged to saparate markers,
the number inside a marker represent number of cars avialable at that parking spot,
the number inside a cluster represent sum of number of cars avialable at the clustered parking spots.
a marker labaled as a car represent a car located by its adress.

**Comment by giladDAN** [comment]
it's should not show cluster and marker in the same view, think about customers and what they will understand.
just small change to cluster on a certain zoom (all points)

**Comment by galsinai128** [comment]
you right, I thougt it wont look good with to many markers on screen from zoom but its much better ux when adding the ristriction.
